spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopzone?useSSL=false&serverTimezone=UTC
    username: root
    password: nguyenhuudat
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  mail:
    host: smtp.office365.com
    port: 587
    username: shopzone.ecommere@hotmail.com
    password: ShopZone123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8080

jwt:
  expiration: 86400000
  refreshExpiration: 604800000