spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopzone?useSSL=false&serverTimezone=UTC
    username: root
    password: nguyenhuudat
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: shopzoneecommerce@gmail.com
    password: jatjufpfqdhwoabx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection timeout: 5000
          timeout: 3000
          write timeout: 5000

server:
  port: 8080

jwt:
  expiration: 86400000
  refresh_expiration: 604800000

cloudinary:
  cloud_name: shopzone
  api_key: 973372223751517
  api_secret: k6fAXGJxxUSMV8GCGYFuAhA8DtI