name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.13.1'

    - name: Install dependencies
      run: yarn install
      working-directory: frontend/admin

    - name: Build project
      run: yarn run build
      working-directory: frontend/admin

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_SHOPZONE_ADMIN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting
      working-directory: frontend/admin
